[project]
name = "cqg-test"
version = "0.1.0"
description = "Technical Assignment for Software developer in autotest department (SDET) at CQG (Broadridge)"
readme = "README.md"
authors = [
    { name = "Jose Luis Cambil", email = "joseluiscc103@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pytest>=9.1.1",
]

[project.scripts]
cqg-test = "cqg_test:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
